### ISSUE TITLE
Issue when restoring demo_data.backup

### ISSUE THREAD

**Issue by rbovard** [qgep/QGEP#595]
Hello,

I generated the datamodel with `db_setup.sh` as described in the doc and now I want to restore the demo data.

So I downloaded `qgep_v1.5.2_demo_data.backup` and tried to restore it but I have a lot of errors:

```
$ pg_restore --dbname=qgep ~/Downloads/qgep_v1.5.2_demo_data.backup 
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 6225; 0 28171 TABLE DATA cover postgres
pg_restore: error: COPY failed for table "cover": ERROR:  function st_x(public.geometry) does not exist
LINE 1: SELECT ST_SetSRID( ST_MakePoint( ST_X(NEW.situation_geometry...
                                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT ST_SetSRID( ST_MakePoint( ST_X(NEW.situation_geometry), ST_Y(NEW.situation_geometry), COALESCE(NEW.level,'NaN') ), 2056)
CONTEXT:  PL/pgSQL function qgep_od.synchronize_level_with_altitude_on_cover() line 5 at assignment
COPY cover, line 1: "ch13p7mzCO000002	\N	\N	0	\N	0.000	\N	5349	01010000A008080000874E821D6BFB4441CCFF6BAAAE4D334100000000..."
pg_restore: from TOC entry 6405; 0 28786 TABLE DATA wastewater_node postgres
pg_restore: error: COPY failed for table "wastewater_node": ERROR:  function st_x(public.geometry) does not exist
LINE 1: SELECT ST_SetSRID( ST_MakePoint( ST_X(NEW.situation_geometry...
                                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT ST_SetSRID( ST_MakePoint( ST_X(NEW.situation_geometry), ST_Y(NEW.situation_geometry), COALESCE(NEW.bottom_level,'NaN') ), 2056)
CONTEXT:  PL/pgSQL function qgep_od.synchronize_level_with_altitude_on_wastewater_node() line 5 at assignment
COPY wastewater_node, line 1: "ch13p7mzWN003457	\N	\N	01010000A0080800001BCC6D5F77FA4441864B51FBE14A3341000000000000F87F\N"
pg_restore: from TOC entry 6407; 0 28808 TABLE DATA wastewater_structure postgres
pg_restore: error: COPY failed for table "wastewater_structure": ERROR:  insert or update on table "wastewater_structure" violates foreign key constraint "rel_wastewater_structure_main_wastewater_node"
DETAIL:  Key (fk_main_wastewater_node)=(ch13p7mzWN006889) is not present in table "wastewater_node".
pg_restore: from TOC entry 6396; 0 28725 TABLE DATA structure_part postgres
pg_restore: error: COPY failed for table "structure_part": ERROR:  insert or update on table "structure_part" violates foreign key constraint "rel_structure_part_wastewater_structure"
DETAIL:  Key (fk_wastewater_structure)=(ch13p7mzMA010436) is not present in table "wastewater_structure".
pg_restore: from TOC entry 6208; 0 28072 TABLE DATA access_aid postgres
pg_restore: error: COPY failed for table "access_aid": ERROR:  insert or update on table "access_aid" violates foreign key constraint "oorel_od_access_aid_structure_part"
DETAIL:  Key (obj_id)=(ch13p7mzAA000002) is not present in table "structure_part".
pg_restore: from TOC entry 6406; 0 28798 TABLE DATA wastewater_networkelement postgres
pg_restore: error: COPY failed for table "wastewater_networkelement": ERROR:  insert or update on table "wastewater_networkelement" violates foreign key constraint "rel_wastewater_networkelement_wastewater_structure"
DETAIL:  Key (fk_wastewater_structure)=(ch13p7mzCL003106) is not present in table "wastewater_structure".
pg_restore: from TOC entry 6218; 0 28130 TABLE DATA catchment_area postgres
pg_restore: error: COPY failed for table "catchment_area": ERROR:  insert or update on table "catchment_area" violates foreign key constraint "rel_catchment_area_wastewater_networkelement_ww_current"
DETAIL:  Key (fk_wastewater_networkelement_ww_current)=(ch13p7mzWN010716) is not present in table "wastewater_networkelement".
pg_restore: from TOC entry 6220; 0 28146 TABLE DATA channel postgres
pg_restore: error: COPY failed for table "channel": ERROR:  insert or update on table "channel" violates foreign key constraint "oorel_od_channel_wastewater_structure"
DETAIL:  Key (obj_id)=(ch13p7mzCL013770) is not present in table "wastewater_structure".
pg_restore: from TOC entry 6278; 0 28446 TABLE DATA reach_point postgres
pg_restore: error: COPY failed for table "reach_point": ERROR:  insert or update on table "reach_point" violates foreign key constraint "rel_reach_point_wastewater_networkelement"
DETAIL:  Key (fk_wastewater_networkelement)=(ch13p7mzWN001608) is not present in table "wastewater_networkelement".
pg_restore: from TOC entry 6231; 0 28200 TABLE DATA discharge_point postgres
pg_restore: error: COPY failed for table "discharge_point": ERROR:  insert or update on table "discharge_point" violates foreign key constraint "oorel_od_discharge_point_wastewater_structure"
DETAIL:  Key (obj_id)=(ch13p7mzDP000002) is not present in table "wastewater_structure".
pg_restore: from TOC entry 6256; 0 28332 TABLE DATA manhole postgres
pg_restore: error: COPY failed for table "manhole": ERROR:  insert or update on table "manhole" violates foreign key constraint "oorel_od_manhole_wastewater_structure"
DETAIL:  Key (obj_id)=(ch13p7mzMA009153) is not present in table "wastewater_structure".
pg_restore: from TOC entry 6277; 0 28439 TABLE DATA reach postgres
pg_restore: error: COPY failed for table "reach": ERROR:  function st_length(public.geometry) does not exist
LINE 1: ...COALESCE(sqrt((_rp_from_level - _rp_to_level)^2 + ST_Length(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT COALESCE(sqrt((_rp_from_level - _rp_to_level)^2 + ST_Length(NEW.progression_geometry)^2), ST_Length(NEW.progression_geometry) )
CONTEXT:  PL/pgSQL function qgep_od.calculate_reach_length() line 17 at assignment
COPY reach, line 1: "ch13p7mzRE000431	500	\N	\N	5378	5383	0.48	3256	01090000A008080000010000000102000080020000005144829D2..."
pg_restore: from TOC entry 6395; 0 28721 TABLE DATA special_structure postgres
pg_restore: error: COPY failed for table "special_structure": ERROR:  insert or update on table "special_structure" violates foreign key constraint "oorel_od_special_structure_wastewater_structure"
DETAIL:  Key (obj_id)=(ch13p7mzSS000002) is not present in table "wastewater_structure".
pg_restore: warning: errors ignored on restore: 13
```

I checked if PostGIS is really installed and it is:

```
# \dx
                                     List of installed extensions
  Name   | Version |   Schema   |                             Description                             
---------+---------+------------+---------------------------------------------------------------------
 hstore  | 1.5     | public     | data type for storing sets of (key, value) pairs
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgis | 2.5.2   | public     | PostGIS geometry, geography, and raster spatial types and functions
(3 rows)
```

What am I missing?

Thanks in advance!

**Comment by rbovard** [comment]
Thanks a lot for the investigations @ponceta!

So something need to be fixed on shell script and/or in demo data dump to be able to test QGEP?

**Comment by ponceta** [comment]
You could roll back to commit 1.5.2 and try restore demo data, but I would better use demodata+structure 1.5.2 (Right clic restore in pgAdmin) for tests purposes, and follow master till 1.5.3 or 1.6.0 (which will come fast if https://github.com/QGEP/datamodel/pull/146 is fixed and commited)

Latest master with latest commits are requiring latest version of pirogue to run smoothly if you encounter any troubles.

I'm currently going through the update process from 1.3.2 -> master to check diffs and new stuff.

If you have any doubts about differences between databases, `pum check` is a simple way of comparing databases.

There's nothing to fix here except maybe the installation documentation (a priori)

**Comment by rbovard** [comment]
Thanks for your idea @ponceta 

> You could roll back to commit 1.5.2 and try restore demo data

I did that (drop DB, checkout v1.5.2, initialize with `db_setup.sh`) but I still have the same error on the restore.

The only difference in the output error is concerning a record (nothing else about the schema)

```
COPY wastewater_node, line 1: "ch13p7mzWN003457	\N	\N	01010000A0080800001BCC6D5F77FA4441864B51FBE14A3341000000000000F87F\N"
```

```
COPY wastewater_node, line 1: "ch13p7mzWN003457	\N	\N	01010000A0080800001BCC6D5F77FA4441864B51FBE14A3341000000000000F87F	\N"
```

**Comment by m-kuhn** [comment]
Use psql instead of pgadmin interface to do a sql import. Use pgadmin for .backup imports

**Comment by rbovard** [comment]
Sorry @m-kuhn, I'm not sure to understand.

I'm restoring with `$ pg_restore --dbname=qgep ~/Downloads/qgep_v1.5.2_demo_data.backup`

You're suggesting to do it with pgadmin GUI?

**Comment by m-kuhn** [comment]
Strange, I thought the above error was caused by an import from a `.sql` file. Not sure how that happens with the command you have here.

**Comment by ponceta** [comment]
Hi @rbovard, I suggest you check again with the 1.5.3 datamodel and demo data:

https://github.com/QGEP/datamodel/releases/tag/1.5.3

I'll do the check on my side tomorrow. I'll comment here if I encounter anything strange.

**Comment by rbovard** [comment]
Hi @ponceta, did you manage to import demo data with success?

**Comment by ponceta** [comment]
Yes, don't hesitate to call me if you encounter some issues when initializing or when restoring demo data.

**Comment by rbovard** [comment]
For the record I'm facing the same issue when restoring 1.5.4 demo data in 1.5.4 datamodel.

```
$ pg_restore --dbname=qgep ../data/qgep_1.5.4_demo_data.backup
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 6225; 0 28173 TABLE DATA cover postgres
pg_restore: error: COPY failed for table "cover": ERROR:  function st_x(public.geometry) does not exist
LINE 1: SELECT ST_SetSRID( ST_MakePoint( ST_X(NEW.situation_geometry...
                                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

...

pg_restore: warning: errors ignored on restore: 13
```

PostGIS 2.5.2 is enabled in database (`# \dx`)

**Comment by sjib** [comment]
Can you test if ST_X function is working (https://postgis.net/docs/ST_X.html)  e.g. with:
`SELECT ST_X(situation_geometry) from qgep_od.wastewater_node;`

**Comment by m-kuhn** [comment]
@rbovard did you `create extension postgis` in this database?

**Comment by rbovard** [comment]
Hi @sjib 

Thanks for your idea, I already did something similar:

```
# SELECT ST_X(ST_GeomFromText('POINT (2600000 1200000)', 2056));
  st_x
---------
 2600000
(1 row)
```

**Comment by rbovard** [comment]
> @rbovard did you `create extension postgis` in this database?

Yes, like I said:
> PostGIS 2.5.2 is enabled in database (# \dx)

**Comment by m-kuhn** [comment]
Not sure how this could be linked to the error here, but did you also try the qgep_1.5.4_structure_and_demo_data.backup ?

**Comment by rbovard** [comment]
@m-kuhn Hum... You know what... It's working!!

I don't understand, but thanks...

FYI the only thing I didn't do is `./scripts/db_setup.sh -r` after the DB creation. Does it rings something on your side?

**Comment by m-kuhn** [comment]
A misalignment of the db_setup.sh created model and the model of the data in the dump? Not exactly sure without having a deeper look.
Should we close this issue?

**Comment by ponceta** [comment]
I'm looking it right now, I will provide some more information, this regards the linux initialization.

@rbovard did you initialize with : ./scripts/db_setup.sh -s 2056 ?

**Comment by ponceta** [comment]
From what I see, it seems difficult to restore qgep_demo_data.backup into a previously generated datamodel, even on the same datamodel tag (I tried using 1.5.4 for both model and demo_data dump).

The restoration throws errors due to qgep model data rules like foreign keys and stuff. @rbovard sorry for leading you to this dead end!

`2021-03-15 07:12:33 CET ERREUR:  une instruction insert ou update sur la table « reach_point » viole la contrainte de clé
	étrangère « rel_reach_point_wastewater_networkelement »`

`2021-03-15 07:20:17 CET ERREUR:  le schéma « qgep_sys » existe déjà`

`2021-03-15 07:32:11 CET ERREUR:  la fonction st_x(public.geometry) n'existe pas au caractère 34`

```
2021-03-15 07:32:11 CET ERREUR:  une instruction insert ou update sur la table « wastewater_structure » viole la contrainte de clé
	étrangère « rel_wastewater_structure_main_wastewater_node »
```

```
2021-03-15 07:32:13 CET ERREUR:  une instruction insert ou update sur la table « wastewater_networkelement » viole la contrainte de clé
	étrangère « rel_wastewater_networkelement_wastewater_structure »
```

Following this, we should either (1) fully support data restoration or (2) avoid releasing demo_data.backup.

I would be in favor of the (2) second option, since even with actual pum we dump and restore the entire database.

**Comment by ponceta** [comment]
I successfully initialized qgep datamodel structure with 1.5.4 using :

`./scripts/db_setup.sh -s 2056 -r`

**Comment by m-kuhn** [comment]
Thanks for the analysis @ponceta

**Comment by rbovard** [comment]
Thanks @ponceta for your feedback and analysis.

> I successfully initialized qgep datamodel structure with 1.5.4 using :
> 
> `./scripts/db_setup.sh -s 2056 -r`

I don't think it change anything, I think it's the default value (see [here](https://github.com/QGEP/datamodel/blob/master/scripts/db_setup.sh#L20)). For the record, the `./scripts/db_setup.sh -r` works fine here and I have the same error after with or without `-s 2056`

The error I'm facing is on the restore, like your's `2021-03-15 07:32:11 CET ERREUR: la fonction st_x(public.geometry) n'existe pas au caractère 34` so somehting is wrong with the shipped `qgep_<tag>_demo_data.backup` and the call to geom queries...

@m-kuhn 
> Should we close this issue?

As @ponceta  suggest, the issue can be handled by

> Following this, we should either (1) fully support data restoration or (2) avoid releasing demo_data.backup.
> 
> I would be in favor of the (2) second option, since even with actual pum we dump and restore the entire database.

It would avoid some frustations on people trying QGEP like me:
- Initialize an empty datamodel to be ready for a futur migration
- Load some provided demo data to have a look for testing purpose

@ponceta 
> sorry for leading you to this dead end!

No worries, you tried to help me ;)

**Comment by m-kuhn** [comment]
Thanks, the subject has been raised here for internal review, we'll keep this open.
